crossplane-contrib/provider-helm

- apis/v1alpha1/types.go
- config/crd/helm.crossplane.io_releases.yaml
- go.sum
- pkg/clients/helm/client.go
- pkg/controller/observe.go
- pkg/controller/observe_test.go
- pkg/controller/patch.go
- pkg/controller/patch_test.go
- pkg/controller/release.go
Add logic to get shaSum of all computed post render hook patches and trigger helm upgrade when there is a change.
Resolves #11
> Trigger upgrade when kustomize patches are modified

- Makefile
Now that the build submodule handles starting a local dev env we should
remove the commands that provide similar functionality without it.
These also look like they were using `provider-gcp` anyway :)
> Remove local dev commands that do not use build sumodule

- .github/workflows/tag.yml
Configures the upbound-bot git user in the tag action before calling
make tag which assumes an already configured git user.
I have:
Closely mimics behavior here: https://github.com/crossplane/crossplane/blob/f220ea959420af58ee0bcdcf9ad709fcbfc72ad3/Jenkinsfile.tag#L20
It appears to me that the[`GITHUB_TOKEN`](https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) permissions do not allow for tagging, but there are some actions that appear to use it, so it is possible this could be improved.
> Configure upbound-bot git user in tag action

- .github/workflows/tag.yml
Configures the upbound-bot git user in the tag action before calling
make tag which assumes an already configured git user.
(cherry picked from commit 9475b92f67bd008ead2993a46954fb868b98a92d)
Fixes #
I have:
> [release-0.3] Configure upbound-bot git user in tag action

- apis/release/v1alpha1/types.go
- package/crds/helm.crossplane.io_releases.yaml
Preserve unknown fields in Helm values.
Otherwise the values will be dropped by the API as all its fields are unknown (no schema). This behavior changed with the v1 CRD introduced in #65 .
See also: https://github.com/crossplane/crossplane/blob/master/apis/apiextensions/v1beta1/composition_types.go#L85
I have:
Manually on a cluster.
> Preserve unknown fields in Helm values

- go.sum
- pkg/controller/release/release.go
Only mark a release as available once all connection details are ready.
Fixes #81 
I have:
Tested on cluster. Both with a `Release` containing `connectionDetails` and one without any.
> Mark Release available with connection details

- examples/in-composition/cluster.yaml
- examples/in-composition/definition.yaml
Signed-off-by: Eric Charles <eric@datalayer.io>
This update the definition of the wordpresscluster example to `apiextensions.crossplane.io/v1` - The current `apiextensions.crossplane.io/v1alph1` is no more available with the latest crossplane release.
The schema of the yaml has changes, so `examples/in-composition/definition.yaml` is updated accordingly.
I have:
I have successfully tested on my local env deploying a GKE cluster and having the wordpress UI available.
> update the in-composition definition to v1 spec

- Makefile
- cluster/integration/integration_tests.sh
This PR improves our integration testing script (by following [this PR](https://github.com/crossplane/provider-aws/pull/711))and fixes [an issue](https://github.com/crossplane/provider-aws/pull/782#issuecomment-888612043) causing e2e checks to fail.
I have:
By observing Github actions e2e check status.
> Integration test fixes and improvements

- apis/release/v1beta1/types.go
- apis/release/v1beta1/zz_generated.deepcopy.go
- package/crds/helm.crossplane.io_releases.yaml
- pkg/clients/helm/client.go
- pkg/controller/release/release.go
- pkg/controller/release/release_test.go
This adds a new field `WaitTimeout` that specifies the timeout for the
helm client actions. If not set it will fall back to a default value in
order to fix #103.
I have:
> Add WaitTimeout field

- apis/release/v1beta1/types.go
- examples/provider-config/provider-config-with-secret.yaml
- examples/sample/release.yaml
- package/crds/helm.crossplane.io_releases.yaml
- pkg/clients/helm/args.go
- pkg/clients/helm/client.go
- pkg/controller/release/release.go
- pkg/controller/release/release_test.go
Signed-off-by: Timofey Ilinykh <ilinytim@gmail.com>
This PR adds the ability to skip the installation of CRDs for a Release.
It is configured by `spec.forProvider.skipCRDs` field (`=false` by default).
The effect is equal to Helm's [`--skip-crds`](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) option
Fixes #107 
I have:
Tested against local dev cluster using the example chart with CRD templates (examples/sample/release-with-crds.yaml).
> Add option to skip CRDs in a Release

- apis/release/v1beta1/types.go
- examples/sample/release-oci.yaml
- package/crds/helm.crossplane.io_releases.yaml
- pkg/clients/helm/args.go
- pkg/clients/helm/client.go
- pkg/controller/release/release.go
This pull request aims to add support for pulling helm charts from OCI registries. 
In addition, the pull request also adds support for pulling charts from insecure registries by adding the option `insecureSkipTLSVerify` to the Release manifest
Since helm 3.8.0 needed some newer dependencies I decided to include a dependency upgrade in this PR as well. If it is preferable to have them as separate pull requests I can split them.
* ~How should we handle insecure registries?~
* ~Should we also add support for defining the url option with `oci://` prefixed protocol? And if that is the case, should we require it to define the full tar file path?  Or support the url to be defined as `oci://localhost:5000/myrepo/mychart:2.7.0`~ 
Fixes #75 
I have:
Following manual tests have been performed:
* …
> Add support for OCI charts

- cluster/images/provider-helm-controller/Dockerfile
- cluster/integration/integration_tests.sh
Signed-off-by: Mathias Åhsberg <mathias.ahsberg@resurs.se>
When deploying a helm chart from an OCI registry with credentials the Release will fail with the following error:
> Warning  CannotCreateExternalResource  4s (x16 over 54s)  managed/release.helm.crossplane.io  failed to install release: failed to login to registry: mkdir /.config: permission denied
It is raised when Helm is trying to create the config folder to be used for storing auth details for the registry. 
By setting the `XDG_CONFIG_HOME ` to the `/tmp` folder in the Dockerfile we can be sure that the user running the container has permission to create the required folders.
See https://github.com/helm/helm/issues/8038 for a related issue
I have:
The PR has now been verified with installing a helm chart from a secured ECR …
> Set config home in Dockerfile

- Makefile
- cluster/integration/integration_tests.sh
- cluster/local/kind.yaml
- examples/sample/release.yaml
- pkg/clients/helm/client.go
Helm provides the ability to specify `--devel` flag to also include development versions (alpha, beta, and release candidate releases).
Under the hood, `--devel` is equivalent to version `>0.0.0-0`.
I have added the option to specify this version in the chart and to pull the latest development version from a helm registry.
I have tested it with local Kind cluster & a private helm registry which contains an `-rc` chart.
Fixes #
I have:
- [ V] Read and followed Crossplane's [contribution process].
- [V ] Run `make reviewable` to ensure this PR is ready for review.
> Support helm devel versions.

- package/crossplane.yaml
Drops the doc.crds.dev link now that content is automatically shown in marketplace.upbound.io when new versions are pushed.
I have:
Verified updated content renders correctly.
> Drop doc.crds.dev link as content is viewed alongside docs now

- .github/workflows/ci.yml
- .github/workflows/promote.yml
- Makefile
Updates Makefile to push to crossplane-contrib.
Updates CI to use the contrib Docker user credentials.
I have:
I have verified these changes work correctly in other repositories.
> Update to push to crossplane-contrib repos

- .github/dependabot.yml
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Add dependabot configuration for dependency management
I have:
This configuration works in the provider-terraform repository.
> Add dependabot for dependency updates

- pkg/clients/helm/client.go
Signed-off-by: Bob Haddleton <bob.haddleton@nokia.com>
Set the uninstall client timeout and wait parameters to the specified args,
The default timeout is null which causes the helm client to wait forever for delete hooks which may never complete if the cluster has been deleted.
Fixes #151 
I have:
Soaked in our development environment for a week, which usually sees the problem multiple times. 
> Set timeout for uninstall client so delete hooks don't hang.

- apis/release/v1beta1/types.go
- examples/sample/release-oci.yaml
- examples/sample/release.yaml
- package/crds/helm.crossplane.io_releases.yaml
- pkg/controller/release/observe.go
- pkg/controller/release/observe_test.go
Add ability to skip 'is part of release' check for manually (non-helm managed) created resource when generating ConnectionDetails.
PS. Field **skipPartOfReleaseCheck** added to _ConnectionDetail_ struct instead of _ReleaseParameters_ (which makes more sense IMHO) because there is we cannot (or can but I'm do not know how? :-) ) access _ReleaseParameters_ from _connectionDetails_ function.
Fixes #99 
I have:
Added 'Success_NotPartOfReleaseAndSkipPartOfReleaseCheck' test to observe_test.go.
> Optionally skip 'partOfRelease' check

- pkg/clients/helm/restclientgetter.go
* Fixes #159
* No more client-side throttling timeouts like
```
I1128 12:44:10.336621       1 request.go:665] Waited for 11.188964474s due to client-side throttling, not priority and fairness, request: GET:https://10.255.0.1:443/apis/cloudidentity.cnrm.cloud.google.com/v1beta1?timeout=32s
I1128 12:44:20.345096       1 request.go:665] Waited for 5.989111872s due to client-side throttling, not priority and fairness, request: GET:https://10.255.0.1:443/apis/binaryauthorization.cnrm.cloud.google.com/v1beta1?timeout=32s
I1128 12:44:31.086707       1 request.go:665] Waited for 1.174828735s due to client-side throttling, not priority and fairness, request: GET:https://10.255.0.1:443/apis/servicedirectory.cnrm.cloud.google.com/v1beta1?timeout=32s
```
* 300 value is aligned with associated kubectl …
> Configure higher burst limit to avoid client side throttling

- README.md
Since `0.13.0` the images don't seem to be pushed to `crossplanecontrib/provider-helm` but to `crossplane/provider-helm` instead.
> Update docker repository

- Makefile
Fix the default Makefile target so `make` runs successfully on a freshly cloned repository.
Partially Fixes: #191 
I have:
Verified that `make` executes successfully on a freshly cloned repository.
> Fix Makefile default target.

- examples/provider-config/provider-config-incluster.yaml
- examples/provider-config/provider-incluster.yaml
use crossplane native way to grant a static service account the needed cluster-admin rights
Fixes #
I have:
> feat(in-cluster): update example to use native crossplane way

- OWNERS.md
This PR simply adds an OWNERS.md file with the current set of contributors that have maintainer permissions. This will make it easier for new contributors to understand who is a maintainer in this repo.
I have:
> Add OWNERS.md file with current maintainers

- cmd/provider/main.go
- pkg/controller/release/observe.go
- pkg/controller/release/observe_test.go
- pkg/controller/release/release.go
This PR is adding support for Management Policies that allows to install a Helm chart and ignore any changes to it and still have healthy managed resource. This is useful if you want to perform the initial installation of the Helm chart via Crossplane (e.g. during bootstrap of a cluster) but later want to manage it via GitOps tool (e.g. ArgoCD or FluxCD).  If the Helm chart is uninstalled via GitOps or via Helm chart client, Crossplane will make sure the chart is installed again.
Fixes #209
I have:
I have build the image and tested it on a local K3D cluster with different sets of `managementPolicies`. If `managementPolicies: [Create, Delete, Observe]`, I can change the version and/or the values of the Helm chart and Crossplane doesn't reinstall it and still keeps the managed resource …
> Adding support for managementPolicies (fixes #209)

- .github/workflows/ci.yml
- cluster/images/provider-helm/Makefile
Allow other build systems to pass additional `--build-arg` to `docker buildx`.
I have:
local `make build` and inspection
> allow additional build arguments

- .gitmodules
- .golangci.yml
- Makefile
Switch build submodule URL to `crossplane/build` and to the commit [d3155548bfab68fc8bea64c5526642b7b565ae33](https://github.com/crossplane/build/commit/d3155548bfab68fc8bea64c5526642b7b565ae33) which includes an update of `golangci-lint` to `1.61.0` to fix problems linting on macOS (arm64). See https://github.com/crossplane/build/pull/23
Also includes the following deprecation fixes:
- Update `.golangci.yml` config for several deprecated config settings
- Removed archived/deprecated linter `interfacer`
- Replaced `megacheck` with `gosimple`, `staticcheck`, and `unused`
I have:
CI & `make lint` in local machine
> consume golangci-lint 1.61.0

- apis/release/v1alpha1/types.go
- apis/release/v1beta1/types.go
As mentioned in https://github.com/crossplane/function-sdk-go/issues/161 and further https://github.com/go-json-experiment/json/pull/39 "inline,omitempty" is an invalid combination of json tags. This leads to issues in marshaling DataKeySelector. 
I have:
We have tested the modified types.go locally in our e2e tests. This shouldn't be a breaking change as it wasn't working in crossplane functions until now. Also CRDs have not changed.
Would appreciate a 0.20 or even 0.19 backport
> fix: remove omitempty in invalid json tag combination

- go.mod
The `go1.23`means automatically consuming the latest patch version. However, in the pipelines we need specific patch version. So, we updated it here.
| Name | Change | Type | Vulnerability | Severity |
|---|---|---|---|---|
| stdlib | `go1.23` -> `go1.23.6` | go-module | CVE-2024-45341 | Medium |
| stdlib | `go1.23` -> `go1.23.6` | go-module | CVE-2024-45336 | Medium |
| stdlib | `go1.23` -> `go1.23.6` | go-module | CVE-2025-22866 | - |
I have:
> (release-0.20): Update go version to 1.23.6 [SECURITY]

- Makefile
Add go.mod.cachedir to Makefile
Fixes: https://github.com/crossplane-contrib/provider-helm/actions/runs/14933624815/job/41955788850
I have:
> Add go.mod.cachedir to Makefile
