crossplane-contrib/provider-helm

Makefile
pkg/controller/release_test.go

Update build submodule to remove helm workaround

---

pkg/clients/client.go

Consume kubeconfig key if found

---

examples/in-composition/cluster-role.yaml
examples/in-composition/cluster.yaml
examples/in-composition/composition.yaml
examples/in-composition/definition.yaml

A Crossplane composition which deploys wordpress using provider-helm.

Add composition example

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml
.github/workflows/golangci-lint.yml

Updates PR and issue templates as well as GitHub workflows and build submodule to match crossplane/crossplane#1775.

Match crossplane/crossplane build and GitHub configuration

---

apis/v1alpha1/zz_generated.pc.go
config/crd/helm.crossplane.io_providerconfigs.yaml
examples/in-composition/composition.yaml
examples/provider-config/local-provider-config.yaml
go.mod
go.sum
pkg/controller/release/release.go
pkg/controller/release/release_test.go

See https://github.com/crossplane/crossplane-runtime/pull/212 for context. 
I have:
I've run through the `examples/in-composition` example.

Use distinct ProviderConfig credentials field

---

go.mod
go.sum

Pins crossplane-runtime to v0.10.0 in anticipation of cutting the
release-0.3 branch.
I have:
n/a

Pin crossplane-runtime to v0.10.0 ahead of v0.3.0 release

---

pkg/controller/release/release.go

Ensure ready condition set if failed first time

---

pkg/clients/client.go

Fix parsing kubeconfig - cluster for context

---

apis/release/v1alpha1/types.go
package/crds/helm.crossplane.io_releases.yaml

Adds printer columns to `kubectl get release` output.
example:
```
NAME           CHART   VERSION   SYNCED   READY   STATE      REVISION   DESCRIPTION        AGE
etcd-cluster   etcd    4.12.0    True     True    deployed   1          Install complete   26m
```
I have:

Add printer columns to release

---

.github/workflows/tag.yml

Updates git remote replace url command by removing escape character and
switching to using * for delimeter in sed to avoid expansion of argument
that also contains slashes.
I have:
Tested command locally :+1: 

Fix git remote replace

---

.github/workflows/tag.yml

Updates git remote replace url command by removing escape character and
switching to using * for delimeter in sed to avoid expansion of argument
that also contains slashes.
(cherry picked from commit f508b6525e3a13b8e8c7d588e4a48a794c3e4e88)
I have:

[release-0.3] Fix git remote replace

---

.github/workflows/tag.yml

Fixes sed expression in tag workflow.
I have:

Fix sed expression in tag workflow

---

.github/workflows/tag.yml

(cherry picked from commit 3e140baea4a0acd6384d8464da8d11dab030da35)
Cherry pick fix 3e140baea4a0acd6384d8464da8d11dab030da35
I have:

[release-0.3] Fix sed in tag workflow

---

pkg/controller/release/release.go

Concurrent processing of helm releases

---

.github/workflows/ci.yml
.github/workflows/promote.yml
.github/workflows/tag.yml

This PR should improve some build times, and fix the promote action. It also allows us more flexibility in the tag names we create - i.e. the action can now be used to create RC tags before cutting a release branch.
I have:

Update CI and Release Actions

---

pkg/controller/release/release.go

Short term solution for [this issue](#58) as described here: https://github.com/crossplane-contrib/provider-helm/issues/58#issuecomment-721083747
I have:

Increase reconcile timeout to 10m

---

pkg/controller/release/release.go

(cherry picked from commit a7810914a2fd3e3e94801149a3bf5cc981cbbaa5)

[release-0.3] Increase reconcile timeout to 10m

---

apis/generate.go
package/crds/helm.crossplane.io_providerconfigs.yaml
package/crds/helm.crossplane.io_providerconfigusages.yaml
package/crds/helm.crossplane.io_releases.yaml

Addresses https://github.com/crossplane/crossplane/issues/1435
I have:
It has not - this is a low risk change that follows the conventions established and tested in https://github.com/crossplane/crossplane/pull/1850.

Use v1 CRDs

---

package/crossplane.yaml

Add package meta.
I have:
Tested in my staging environment.
Signed-off-by: Phil Prasek <prasek@gmail.com>

Add package meta

---

package/crossplane.yaml

Signed-off-by: Phil Prasek <prasek@gmail.com>
(cherry picked from commit b4f9300195bde961add709c297e11ccc7318cd6b)
Fixes #
I have:

[release-0.3] add package meta

---

apis/release/v1alpha1/types.go
apis/release/v1alpha1/zz_generated.managed.go
apis/release/v1beta1/types.go
apis/release/v1beta1/zz_generated.managed.go
apis/v1alpha1/types.go
apis/v1alpha1/zz_generated.pc.go
apis/v1alpha1/zz_generated.pcu.go
apis/v1beta1/types.go
apis/v1beta1/zz_generated.pc.go
apis/v1beta1/zz_generated.pcu.go
go.mod
go.sum
pkg/controller/release/chart.go
pkg/controller/release/chart_test.go
pkg/controller/release/release.go
pkg/controller/release/release_test.go

I have:
It has not - it's a very mechanical change.

Bump crossplane-runtime to v0.12.0

---

apis/release/v1beta1/types.go
examples/sample/release.yaml
package/crds/helm.crossplane.io_releases.yaml
pkg/clients/helm/client.go
pkg/controller/release/release.go

Support URL in chart spec

---

.github/workflows/ci.yml
cmd/provider/main.go
go.mod
go.sum

Fixes "no Auth Provider found" errors like mentioned in https://github.com/crossplane-contrib/provider-helm/issues/84#issuecomment-818871124
This could also be related with #72 
I have:
With a helm release pointing a GKE cluster in provider-config

Add auth helpers

---

apis/release/v1beta1/types.go
cluster/integration/integration_tests.sh
examples/sample/release.yaml
package/crds/helm.crossplane.io_releases.yaml
pkg/clients/helm/client.go
pkg/controller/release/release.go
pkg/controller/release/release_test.go

Add a label to created namespaces.
Fixes #77
Fixes #80
I have:

Label created namespaces

---

examples/in-composition/composition.yaml

Signed-off-by: Eric Charles <eric@datalayer.io>
Follow-up of https://github.com/crossplane-contrib/provider-helm/pull/90 (a file was missing in the PR).

Update the in-composition composition example to v1 api

---

apis/release/v1alpha1/types.go
apis/release/v1beta1/types.go
package/crds/helm.crossplane.io_releases.yaml

Running [crossplane conformance suite](https://github.com/crossplane/conformance) for provider helm failed with:
```
Managed resources must be in the 'managed' CRD category
```
I have:
Deploy changes and re-run conformance tests

Release in managed category

---

apis/release/v1alpha1/types.go
apis/release/v1beta1/types.go
package/crds/helm.crossplane.io_releases.yaml

To be conformant with the following:
Managed resources must be in the 'managed' CRD category
(cherry picked from commit 5d54d2c894b816c0b9648f7dff5a6993798106aa)
I have:

[release-0.7] Release in managed catagory

---

pkg/controller/release/observe.go

Signed-off-by: Dor Mull-or <dormullor@gmail.com>
Upon adding the ability to use devel helm versions, I noticed a bug where the operator is trying to endlessly update the version when comparing the ">0.0.0-0" version to the real helm version.
If this comparison returns false, the controller triggers an unnecessary update.
Fixes #
I have:
- [V ] Read and followed Crossplane's [contribution process].
- [V ] Run `make reviewable` to ensure this PR is ready for review.
Using local Kind kubernetes cluster 

Fix devel bug endless update

---

Makefile

Updates to not run promote on xpkg.upbound.io.
I have:
Fixes error seen in CI runs.

Do not promote images on xpkg.upbound.io

---

package/crossplane.yaml

Just adding the friendly-name.meta.crossplane.io annotation
Fixes #
I have:

chore: add friendly-name.meta.crossplane.io annotation

---

README.md
examples/provider-config/provider-incluster.yaml

Updates package address.
I have:
N/A => just doc update

Update package address

---

go.mod

Update go version to 1.24.6
I have:

Update go version to 1.24.6 [Security]

---

.github/workflows/publish-provider-package.yaml

This PR fixes publish provider package workflow.
I have:

Fix publish provider package workflow
